### ISSUE TITLE
Deleted bike reappears after logging in via Strava

### ISSUE THREAD

**Issue by ptc-gibbs** [deuber/fitBike#2]
If I delete a bike in the FitBike app (on fitbike.herokuapp.com), log out, and log back in via Strava, the bike I deleted reappears on my account.

I assume it's refreshing the data from Strava and adding the missing bike back in.

You should probably consider flagging the bike as deleted instead of physically deleting the record, so you can prevent it from being re-added.

**Comment by deuber** [comment]
Hi Ptc-Gibbs,
You're correct, if you delete a bike within the FitBike app but not also within Strava, the bike will reappear the next time you open FitBike.  I'll put this on my todo list. However, I don't think I'll be able to get to this soon. In the meantime,  you'll need to delete the bike in two locations (FitBike and Strava). Thanks for pointing this out and offering a valid solution.
